# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 04:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0004_auto_20160819_0633'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEncuentro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizador', models.CharField(max_length=128)),
                ('descripcion', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Encuentro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('rut_encargado', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='ItemTema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField(blank=True, null=True)),
                ('pregunta_propuesta', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=128)),
                ('configuracion_encuentro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actas.ConfiguracionEncuentro')),
            ],
        ),
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocupacion', models.CharField(max_length=128)),
                ('configuracion_encuentro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actas.ConfiguracionEncuentro')),
            ],
        ),
        migrations.CreateModel(
            name='Origen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=128)),
                ('configuracion_encuentro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actas.ConfiguracionEncuentro')),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=11)),
                ('nombre', models.CharField(max_length=128)),
                ('apellido', models.CharField(max_length=128)),
                ('correo', models.EmailField(max_length=128)),
                ('numero_de_carnet', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.IntegerField(choices=[(b'Acuerdo', 1), (b'Acuerdo parcial', 0), (b'Desacuerdo', -1)])),
                ('fundamento', models.TextField(blank=True, null=True)),
                ('propuesta', models.TextField(blank=True, null=True)),
                ('encuentro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actas.Encuentro')),
                ('item_tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actas.ItemTema')),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=128)),
                ('contexto', models.TextField(blank=True, null=True)),
                ('configuracion_encuentro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actas.ConfiguracionEncuentro')),
            ],
        ),
        migrations.CreateModel(
            name='TipoEncuentro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=128)),
                ('configuracion_encuentro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actas.ConfiguracionEncuentro')),
            ],
        ),
        migrations.RemoveField(
            model_name='acta',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='participantes',
        ),
        migrations.AlterUniqueTogether(
            name='actarespuestaitem',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='actarespuestaitem',
            name='acta',
        ),
        migrations.RemoveField(
            model_name='actarespuestaitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='comuna',
            name='provincia',
        ),
        migrations.RemoveField(
            model_name='item',
            name='grupo_items',
        ),
        migrations.RemoveField(
            model_name='provincia',
            name='region',
        ),
        migrations.DeleteModel(
            name='Acta',
        ),
        migrations.DeleteModel(
            name='ActaRespuestaItem',
        ),
        migrations.DeleteModel(
            name='Comuna',
        ),
        migrations.DeleteModel(
            name='GrupoItems',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Provincia',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.AddField(
            model_name='itemtema',
            name='tema_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actas.Tema'),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actas.Lugar'),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='tipo_encuentro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actas.TipoEncuentro'),
        ),
    ]
