# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0006_auto_20160903_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='orden',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='categoria',
            field=models.IntegerField(choices=[set(['de_acuerdo', 2]), set([1, 'mayoria_de_acuerdo']), set([0, 'desacuerdo']), set(['mayoria_desacuerdo', -1]), set(['desacuerdo', -2])]),
        ),
    ]
