# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0008_auto_20160904_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuentro',
            name='configuracion_encuentro',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='actas.ConfiguracionEncuentro'),
            preserve_default=False,
        ),
    ]
