# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0009_encuentro_configuracion_encuentro'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuentro',
            name='hash_search',
            field=models.UUIDField(default=b'3250c9c074a511e6aa8740e230d28fea'),
        ),
    ]
