# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0012_auto_20160907_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuentro',
            name='hash_search',
            field=models.UUIDField(default=b'd825d550750b11e6817700163e00aafb'),
        ),
    ]
