# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0013_auto_20160907_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuentro',
            name='hash_search',
            field=models.UUIDField(default=b'e39b001475cd11e69768645a04c2662c'),
        ),
    ]
