# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 01:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0013_auto_20160907_2137'),
        ('actas', '0013_auto_20160907_1500'),
    ]

    operations = [
    ]
