# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-08 19:14
from __future__ import unicode_literals

import actas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0014_auto_20160908_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionencuentro',
            name='created_at',
            field=models.DateTimeField(default=actas.models.default_datetime),
        ),
        migrations.AddField(
            model_name='configuracionencuentro',
            name='updated_at',
            field=models.DateTimeField(default=actas.models.default_datetime),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='created_at',
            field=models.DateTimeField(default=actas.models.default_datetime),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='updated_at',
            field=models.DateTimeField(default=actas.models.default_datetime),
        ),
        migrations.AddField(
            model_name='itemtema',
            name='created_at',
            field=models.DateTimeField(default=actas.models.default_datetime),
        ),
        migrations.AddField(
            model_name='itemtema',
            name='updated_at',
            field=models.DateTimeField(default=actas.models.default_datetime),
        ),
        migrations.AddField(
            model_name='lugar',
            name='created_at',
            field=models.DateTimeField(default=actas.models.default_datetime),
        ),
        migrations.AddField(
            model_name='lugar',
            name='updated_at',
            field=models.DateTimeField(default=actas.models.default_datetime),
        ),
        migrations.AddField(
            model_name='ocupacion',
            name='created_at',
            field=models.DateTimeField(default=actas.models.default_datetime),
        ),
        migrations.AddField(
            model_name='ocupacion',
            name='updated_at',
            field=models.DateTimeField(default=actas.models.default_datetime),
        ),
        migrations.AddField(
            model_name='origen',
            name='created_at',
            field=models.DateTimeField(default=actas.models.default_datetime),
        ),
        migrations.AddField(
            model_name='origen',
            name='updated_at',
            field=models.DateTimeField(default=actas.models.default_datetime),
        ),
        migrations.AddField(
            model_name='participa',
            name='created_at',
            field=models.DateTimeField(default=actas.models.default_datetime),
        ),
        migrations.AddField(
            model_name='participa',
            name='updated_at',
            field=models.DateTimeField(default=actas.models.default_datetime),
        ),
        migrations.AddField(
            model_name='participante',
            name='created_at',
            field=models.DateTimeField(default=actas.models.default_datetime),
        ),
        migrations.AddField(
            model_name='participante',
            name='updated_at',
            field=models.DateTimeField(default=actas.models.default_datetime),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='created_at',
            field=models.DateTimeField(default=actas.models.default_datetime),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='updated_at',
            field=models.DateTimeField(default=actas.models.default_datetime),
        ),
        migrations.AddField(
            model_name='tema',
            name='created_at',
            field=models.DateTimeField(default=actas.models.default_datetime),
        ),
        migrations.AddField(
            model_name='tema',
            name='updated_at',
            field=models.DateTimeField(default=actas.models.default_datetime),
        ),
        migrations.AddField(
            model_name='tipoencuentro',
            name='created_at',
            field=models.DateTimeField(default=actas.models.default_datetime),
        ),
        migrations.AddField(
            model_name='tipoencuentro',
            name='updated_at',
            field=models.DateTimeField(default=actas.models.default_datetime),
        ),
        migrations.AlterField(
            model_name='encuentro',
            name='hash_search',
            field=models.UUIDField(default=b'7f906ecf75f811e6b3b140e230d28fea'),
        ),
    ]
