# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0014_auto_20160908_1409'),
        ('actas', '0014_merge_20160908_0112'),
    ]

    operations = [
    ]
