# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-08 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0015_auto_20160908_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuentro',
            name='hash_search',
            field=models.UUIDField(default=b'c3ffb470761311e6b80740e230d28fea'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='categoria',
            field=models.IntegerField(choices=[('de_acuerdo', 2), ('mayoria_de_acuerdo', 1), ('desacuerdo', 0), ('mayoria_desacuerdo', -1), ('desacuerdo', -2)]),
        ),
    ]
