# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0015_auto_20160908_1614'),
        ('actas', '0015_merge_20160908_1416'),
    ]

    operations = [
    ]
