# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-21 19:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0016_auto_20160908_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaGuardada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name=b'Email')),
                ('propuesta', models.TextField(verbose_name=b'Propuesta')),
                ('created_at', models.DateField(verbose_name=datetime.datetime(2016, 9, 21, 16, 48, 57, 216000))),
            ],
        ),
        migrations.AlterField(
            model_name='encuentro',
            name='hash_search',
            field=models.UUIDField(default=b'6f1c5000803411e6a10940e230d28fea'),
        ),
    ]
