# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 03:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0016_merge_20160908_2037'),
        ('actas', '0016_auto_20160908_1929'),
    ]

    operations = [
    ]
