# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-21 19:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0017_auto_20160921_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actaguardada',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2016, 9, 21, 16, 55, 49, 701000)),
        ),
        migrations.AlterField(
            model_name='encuentro',
            name='hash_search',
            field=models.UUIDField(default=b'64f8874f803511e6b87340e230d28fea'),
        ),
    ]
