# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 20:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0018_auto_20160921_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actaguardada',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2016, 10, 9, 20, 58, 47, 933409)),
        ),
        migrations.AlterField(
            model_name='encuentro',
            name='hash_search',
            field=models.UUIDField(default=b'2c678b348e6311e68bd6645a04c2662c'),
        ),
    ]
