# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 05:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0018_auto_20160921_1655'),
        ('actas', '0017_merge_20160909_0329'),
    ]

    operations = [
    ]
