# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 05:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0019_merge_20160926_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actaguardada',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2016, 9, 28, 5, 39, 21, 950745)),
        ),
        migrations.AlterField(
            model_name='encuentro',
            name='hash_search',
            field=models.UUIDField(default=b'e85f47fc853d11e6af8300163e00aafb'),
        ),
    ]
