# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 05:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0020_auto_20160928_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actaguardada',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2016, 9, 28, 5, 42, 15, 847537)),
        ),
        migrations.AlterField(
            model_name='encuentro',
            name='hash_search',
            field=models.UUIDField(default=b'5005c3cc853e11e695fb00163e00aafb'),
        ),
    ]
