# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 05:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0021_auto_20160928_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actaguardada',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2016, 9, 28, 5, 44, 29, 851242)),
        ),
        migrations.AlterField(
            model_name='encuentro',
            name='hash_search',
            field=models.UUIDField(default=b'9fe51db6853e11e6a55a00163e00aafb'),
        ),
    ]
